name: pygbag_build
on: [workflow_dispatch]


jobs:
  build-pygbag:
    name: Build for Emscripten pygbag runtime
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: |
            python -m pip install pygame-ce
            python -m packitup -s $GITHUB_WORKSPACE/Samples/AsteroidShooter -o $GITHUB_WORKSPACE/web-deploy
            python -m pip install pygbag
            python -m pygbag --build --app_name "Asteroid Continuum 1983" --ume_block 0 --can_close 1 --icon $GITHUB_WORKSPACE/Samples/Assets/favicon.png --template $GITHUB_WORKSPACE/Samples/AsteroidShooter/default.tmpl $GITHUB_WORKSPACE/web-deploy/AsteroidShooter
    - name : "Upload to GitHub pages branch gh-pages"
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: web-deploy/AsteroidShooter/build/web
